const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What do you like to watch today ?",
    signOut: "Sign Out",
    homePage: "Home Page",
    clearAll: "Clear All",
    clear: "Clear Item",
    emptyCart: "Cart is Empty Please Add Movie",
    GptSearch: "GPT Search",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upComing: "Up Coming",
    signUp: "Sing Up",
    signIn: "Sing In",
    namePlaceholder: "Full Name",
    emailPlaceholder: "Email Address",
    passwordPlaceholder: "Password",
    alreadyRegister: "Already Register",
    signInNow: "Sign In Now",
    signUpNow: "Sign Up Now",
    newToNetflix: "New To Netflix",
    cart: "Cart",
    totalMovie: "Total Movies",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना पसंद करते हैं?",
    signOut: "साइन आउट",
    homePage: "मुखपृष्ठ",
    GptSearch: "जीपीटी खोज",
    play: " बजाना",
    moreInfo: "अधिक जानकारी",
    nowPlaying: "अभी चल रहा है",
    popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upComing: "आगामी",
    signUp: "साइन अप करें",
    signIn: "दाखिल करना",
    clearAll: "सभी साफ करें",
    emptyCart: "कार्ट खाली है कृपया मूवी जोड़ें",
    namePlaceholder: "पूरा नाम",
    emailPlaceholder: "मेल पता",
    passwordPlaceholder: "पासवर्ड",
    alreadyRegister: "पहले से ही रजिस्टर करें",
    signInNow: "अब साइन इन करो",
    signUpNow: "अभी साइनअप करें",
    newToNetflix: "नेटफ़्लिक्स पर नया है",
    cart: "कार्ट",
    totalMovie: "फिल्मों की कुल संख्या",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gusta ver hoy?",
    signOut: "Desconectar",
    homePage: "Página Principal",
    GptSearch: "Búsqueda GPT",
    play: "Reproducir",
    moreInfo: "Más Info",
    clearAll: "Limpiar todo",
    emptyCart: "El carrito está vacío. Agregue una película.",
    nowPlaying: "Jugando Ahora",
    popular: "Popular",
    topRated: "Los Más Valorados",
    upComing: "Próximamente",
    signUp: "Inscribirse",
    signIn: "Iniciar Sesión",
    namePlaceholder: "Nombre Completo",
    emailPlaceholder: "Correo Electrónico",
    passwordPlaceholder: "Contraseña",
    alreadyRegister: "Ya Registrado",
    signInNow: "Regístrate",
    signUpNow: "Regístrate Ahora",
    newToNetflix: "Nueva en Netflix",
    cart: "Carro",
    totalMovie: "Película Total",
  },
};

export default lang;
